# Generated by Django 5.2.3 on 2025-06-22 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='firearms/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_available', models.IntegerField(choices=[(0, 'Not available'), (1, 'Available')], default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.category')),
            ],
        ),
    ]
